### ISSUE TITLE
implement --version

### ISSUE THREAD

**Issue by medyagh** [lima-vm/socket_vmnet#15]
Hi, thank you for adding binaries to the release page, we are excited to look into using it !

https://github.com/lima-vm/socket_vmnet/issues/10

I would like to know if we could have a "--version" or "version" command to see what version it is installed, so we could update or tell user to update their socket_vmnet

**Comment by AkihiroSuda** [comment]
We already have
https://github.com/lima-vm/socket_vmnet/blob/efae13851e0c7cc655f7ebbeb5e8f7412a448846/cli.c#L57-L58
