### ISSUE TITLE
mac address in bridged mode

### ISSUE THREAD

**Issue by chetan-reddy** [lima-vm/socket_vmnet#32]
I'm using --vmnet-mode=bridged, and my debian bookworm guest is able to get an IP that's in the same subnet as the macos(11.7.8) host. While it "works", I see that my router's dhcp server sees both the macos host and the debian guest IPs on the same MAC address. This MAC address is the same as the bridged interface's MAC address on the macos host. Using the arp command, I've verified that other hosts on my network also see the same mac address for both the macos host IP and the debian guest IP. Am I doing something wrong? After some digging, I found that Parallels also had a similar issue with the vmnet framework for a bit before they resolved it. You can see reports here -> https://forum.parallels.com/threads/pd16-on-big-sur-vm-not-using-the-configured-mac-address.351236/

**Comment by nirs** [comment]
@chetan-reddy can you add more details?
- how do you create the guest?
- what is the output of `ip a` in the guest?
- what is arp output on the host?

**Comment by chetan-reddy** [comment]
@nirs I was using qemu on macos to run the debian guest , but I've since completely switched over from macos to linux so I can no longer help debug this. Sorry. I'm going to close this issue.
