### ISSUE TITLE
Update docs and launchd configuration - stdout not used 

### ISSUE THREAD

**Issue by nirs** [lima-vm/socket_vmnet#70]
Since #58 we log only to stderr, so /var/log/socket_vmnet/stdout is never used.

- [ ] Remove from README.md
- [ ] Remove from launchd configuration

**Comment by AkihiroSuda** [comment]
We may still accidentally have some output in stdout, so I suggest keeping the stdout log too.

**Comment by nirs** [comment]
Ok, maybe just add a node that we log to stderr and stdout is unused.
