### ISSUE TITLE
ERROR: Failed to connect to "/var/run/socket_vmnet": Permission denied

### ISSUE THREAD

**Issue by spowelljr** [lima-vm/socket_vmnet#8]
I've been using socket_vmnet without issue for a couple months, but every time I try using it now I get:
`Failed to connect to "/var/run/socket_vmnet": Permission denied`

```
$ /opt/socket_vmnet/bin/socket_vmnet_client /var/run/socket_vmnet qemu-system-aarch64
Failed to connect to "/var/run/socket_vmnet": Permission denied
```

I recently updated to macOS 12.6.1, may have been a coincidence (I tried on a machine with 13.0 and it works). A coworker has also been experiencing this for a little while (before 12.6.1).

I ran `make uninstall` and manually removed `/var/run/socket_vmnet`, restarted my computer, reinstalled, but still the same error.

```
$ ls -l /var/run
srwxrwx---   1 root          staff           0 Oct 28 10:43 socket_vmnet
-rw-r--r--   1 root          daemon          0 Oct 28 10:43 socket_vmnet.stderr
-rw-r--r--   1 root          daemon          0 Oct 28 10:43 socket_vmnet.stdout
```

**Comment by AkihiroSuda** [comment]
You aren't in the "staff" group?

**Comment by spowelljr** [comment]
> You aren't in the "staff" group?
If so, is your account managed by your company?

Thank you for the comment @AkihiroSuda, you made me realize for the first time that the user groups on my machine are very different than a standard Mac, `staff` isn't user anywhere. I `chown` the the socket to my corp group and it works now, very odd that it just started happening and was working fine previously with the `staff` group.
