### ISSUE TITLE
`make artifacts` should not depend on GNU tar and GNU coreutils

### ISSUE THREAD

**Issue by AkihiroSuda** [lima-vm/socket_vmnet#81]
https://github.com/lima-vm/socket_vmnet/blob/8664a96cc2b23d9bce989e8e8955492bc855ac09/Makefile#L5-L7

**Comment by nirs** [comment]
`brew install gnu-tar` fixes the issue. If we document it I don't see the issue in using it.

We can add CONTRIBUTING.md with info for developers.

**Comment by AkihiroSuda** [comment]
This only affects the CI, so not worth documenting

**Comment by nirs** [comment]
This affects developers that want to try `make artifacts` locally, added #91
