### ISSUE TITLE
v1.2.0 planning

### ISSUE THREAD

**Issue by nirs** [lima-vm/socket_vmnet#93]
We have lot of content for 1.2.0, anything missing for a new release?
https://github.com/lima-vm/socket_vmnet/milestone/8?closed=1

I think the most important for the release is improved logging:
https://github.com/lima-vm/socket_vmnet/pull/46

**Comment by AkihiroSuda** [comment]
Sure, after merging:
- https://github.com/lima-vm/socket_vmnet/pull/94

**Comment by AkihiroSuda** [comment]
https://github.com/lima-vm/socket_vmnet/releases/tag/v1.2.0
