### ISSUE TITLE
how to fix "lima v1.0.1 need socket_vmnet owded by "root""

### ISSUE THREAD

**Issue by Bevisy** [lima-vm/socket_vmnet#95]
when using `brew install socket_vmnet`, socket_vmnet is default owned by current user but not root. So when using `lima`, it will error as below:
```
❯ limactl sudoers
INFO[0000] Please check https://lima-vm.io/docs/config/network/#socket_vmnet for more information.
FATA[0000] networks.yaml field `paths.socketVMNet` error: file "/usr/local/Cellar/socket_vmnet/1.1.7/bin/socket_vmnet" is not owned by "root" (uid: 0), but by uid 501
```

how to fix this?

**Comment by debeetle** [comment]
Same problem for me, can I ask for the final solution please?

**Comment by Bevisy** [comment]
REF: https://lima-vm.io/docs/config/network/vmnet/#socket_vmnet
